/* global React */

const NEXA_ORGS = {
  cb: {
    key: "cb",
    short: "CB",
    name: "Constructora Bolívar",
    id: "ORG-CB-001",
    accent: "#00C2CB",
    description: "División de construcción y desarrollo inmobiliario. Procesa expedientes de lotes, planos, contratos de obra y avalúos.",
    metrics: {
      docs: "2,847", docsDelta: "+18%",
      pages: "42.1k", pagesDelta: "+14%",
      users: 34, usersDelta: "+3",
      validation: 98.4, validationDelta: "+1.2 pts",
      avgTime: "22s", timeDelta: "−8%",
    },
    peakHour: "10:00 – 11:00",
    peakDay: "Miércoles",
    toolUsage: [
      { name: "Nexíficar Masivo",  icon: "🗂️", count: 1842, share: 64 },
      { name: "Validador IA",      icon: "⚡", count: 612,  share: 21 },
      { name: "Editar PDF",        icon: "✏️", count: 248,  share: 9  },
      { name: "Dividir PDF",       icon: "✂️", count: 98,   share: 3  },
      { name: "Eliminar páginas", icon: "🗑️", count: 47,   share: 2  },
    ],
    analysts: [
      { name: "Ana María Rojas",   email: "ana.rojas@cb.com.co",     role: "Líder Expedientes", docs: 342, validation: 98.9, hours: 148, lastActivity: "ahora",     online: true  },
      { name: "Carlos Restrepo",   email: "c.restrepo@cb.com.co",    role: "Analista Sr.",       docs: 298, validation: 97.8, hours: 142, lastActivity: "hace 3 min", online: true  },
      { name: "Diana Salazar",     email: "d.salazar@cb.com.co",     role: "Analista Sr.",       docs: 276, validation: 98.2, hours: 136, lastActivity: "hace 12 min", online: true  },
      { name: "Julián Pardo",      email: "j.pardo@cb.com.co",       role: "Analista Jr.",       docs: 184, validation: 94.1, hours: 128, lastActivity: "hace 22 min", online: true  },
      { name: "Laura Giraldo",     email: "l.giraldo@cb.com.co",     role: "Analista Sr.",       docs: 172, validation: 96.5, hours: 124, lastActivity: "hace 1 h",    online: false },
      { name: "Miguel Ángel Ruiz", email: "m.ruiz@cb.com.co",        role: "Analista Jr.",       docs: 148, validation: 93.2, hours: 118, lastActivity: "hace 2 h",    online: false },
      { name: "Sofía Arango",      email: "s.arango@cb.com.co",      role: "Revisora",            docs: 132, validation: 99.1, hours: 96,  lastActivity: "hace 34 min", online: true  },
      { name: "Tomás Espinoza",    email: "t.espinoza@cb.com.co",    role: "Analista Jr.",       docs: 98,  validation: 91.4, hours: 88,  lastActivity: "ayer",        online: false },
    ],
    feed: [
      { user: "Ana M.",      type: "nexify",   action: "nexificó",              target: "expediente_LT-042",          time: "hace 2 min",  pages: 124, duration: "18s" },
      { user: "Carlos R.",   type: "validate", action: "validó con IA",         target: "contrato_vivienda_8821",     time: "hace 8 min",  pages: 48 },
      { user: "Diana S.",    type: "split",    action: "dividió",               target: "planos_torre_3.pdf",         time: "hace 14 min", pages: 12 },
      { user: "Julián P.",   type: "warn",     action: "reportó inconsistencia en", target: "avaluo_inmueble_77",      time: "hace 22 min", detail: "fecha no coincide con registro" },
      { user: "Laura G.",    type: "edit",     action: "editó",                 target: "contrato_lote_332",          time: "hace 34 min", pages: 22 },
      { user: "Sofía A.",    type: "validate", action: "validó con IA",         target: "cesion_derechos_19",         time: "hace 41 min", pages: 14 },
      { user: "Miguel Á. R.", type: "nexify",   action: "nexificó masivo",       target: "lote_zona_norte_abril",     time: "hace 1 h",    pages: 842, duration: "3m 12s" },
      { user: "Tomás E.",    type: "error",    action: "falló procesamiento de", target: "escritura_114.pdf",          time: "hace 1 h",    detail: "archivo corrupto" },
      { user: "Ana M.",      type: "edit",     action: "redactó datos en",       target: "hipoteca_8822",              time: "hace 2 h",    pages: 6 },
      { user: "Diana S.",    type: "nexify",   action: "nexificó",              target: "expediente_LT-041",          time: "hace 2 h",    pages: 98, duration: "15s" },
    ],
  },
  dv: {
    key: "dv",
    short: "DV",
    name: "Davivienda",
    id: "ORG-DV-002",
    accent: "#0099FF",
    description: "Banco del Grupo Bolívar. Nexifica hipotecas, pagarés, contratos de crédito y documentación de respaldo para análisis de riesgo.",
    metrics: {
      docs: "1,956", docsDelta: "+9%",
      pages: "28.4k", pagesDelta: "+11%",
      users: 21, usersDelta: "+2",
      validation: 97.1, validationDelta: "+0.8 pts",
      avgTime: "28s", timeDelta: "−4%",
    },
    peakHour: "09:00 – 10:00",
    peakDay: "Martes",
    toolUsage: [
      { name: "Validador IA",      icon: "⚡", count: 982,  share: 50 },
      { name: "Nexíficar Masivo",  icon: "🗂️", count: 624,  share: 32 },
      { name: "Editar PDF",        icon: "✏️", count: 212,  share: 11 },
      { name: "Dividir PDF",       icon: "✂️", count: 98,   share: 5  },
      { name: "Eliminar páginas", icon: "🗑️", count: 40,   share: 2  },
    ],
    analysts: [
      { name: "María Lorena Pinto", email: "m.pinto@davivienda.com",  role: "Líder Riesgo",     docs: 264, validation: 98.4, hours: 146, lastActivity: "hace 5 min",  online: true  },
      { name: "Ricardo Vélez",      email: "r.velez@davivienda.com",  role: "Analista Crédito", docs: 221, validation: 97.2, hours: 138, lastActivity: "hace 19 min", online: true  },
      { name: "Sofía Acosta",       email: "s.acosta@davivienda.com", role: "Analista Sr.",     docs: 198, validation: 96.8, hours: 132, lastActivity: "hace 34 min", online: true  },
      { name: "Tomás Estrada",      email: "t.estrada@davivienda.com", role: "Analista Sr.",   docs: 186, validation: 97.5, hours: 128, lastActivity: "hace 41 min", online: true  },
      { name: "Verónica Mejía",     email: "v.mejia@davivienda.com",  role: "Revisora",         docs: 142, validation: 98.9, hours: 104, lastActivity: "hace 1 h",    online: false },
      { name: "Andrés Bernal",      email: "a.bernal@davivienda.com", role: "Analista Jr.",     docs: 98,  validation: 92.4, hours: 92,  lastActivity: "hace 2 h",    online: false },
    ],
    feed: [
      { user: "María L.",    type: "validate", action: "validó con IA",         target: "hipoteca_vivienda_2031",     time: "hace 5 min",  pages: 86 },
      { user: "Ricardo V.",  type: "nexify",   action: "nexificó",              target: "lote_credito_44",            time: "hace 19 min", pages: 48, duration: "22s" },
      { user: "Sofía A.",    type: "edit",     action: "editó",                 target: "pagares_abril_2026",         time: "hace 34 min", pages: 18 },
      { user: "Tomás E.",    type: "validate", action: "validó con IA",         target: "cesion_titulos_09",          time: "hace 41 min", pages: 12 },
      { user: "Verónica M.", type: "warn",     action: "marcó para revisión",   target: "credito_vehiculo_881",       time: "hace 52 min", detail: "firma faltante" },
      { user: "Andrés B.",   type: "nexify",   action: "nexificó masivo",       target: "desembolsos_abril_semana_3", time: "hace 1 h",    pages: 412, duration: "1m 48s" },
      { user: "María L.",    type: "edit",     action: "redactó datos en",      target: "hipoteca_8822",              time: "hace 2 h",    pages: 6 },
      { user: "Ricardo V.",  type: "split",    action: "dividió",               target: "anexos_credito_abril.pdf",    time: "hace 2 h",    pages: 34 },
    ],
  },
  sb: {
    key: "sb",
    short: "SB",
    name: "Seguros Bolívar",
    id: "ORG-SB-003",
    accent: "#A855F7",
    description: "Aseguradora del Grupo Bolívar. Procesa pólizas, siniestros, renovaciones y documentación médica para análisis actuarial.",
    metrics: {
      docs: "1,408", docsDelta: "+24%",
      pages: "18.2k", pagesDelta: "+19%",
      users: 14, usersDelta: "+1",
      validation: 96.0, validationDelta: "+2.4 pts",
      avgTime: "31s", timeDelta: "−11%",
    },
    peakHour: "14:00 – 15:00",
    peakDay: "Jueves",
    toolUsage: [
      { name: "Editar PDF",        icon: "✏️", count: 584,  share: 42 },
      { name: "Validador IA",      icon: "⚡", count: 412,  share: 29 },
      { name: "Nexíficar Masivo",  icon: "🗂️", count: 268,  share: 19 },
      { name: "Dividir PDF",       icon: "✂️", count: 98,   share: 7  },
      { name: "Eliminar páginas", icon: "🗑️", count: 42,   share: 3  },
    ],
    analysts: [
      { name: "Laura Gutiérrez",    email: "l.gutierrez@sb.com.co",   role: "Líder Suscripción", docs: 198, validation: 98.2, hours: 144, lastActivity: "hace 11 min", online: true  },
      { name: "Felipe Torres",      email: "f.torres@sb.com.co",      role: "Analista Siniestros", docs: 172, validation: 97.0, hours: 138, lastActivity: "hace 27 min", online: true  },
      { name: "Valentina Castro",   email: "v.castro@sb.com.co",      role: "Analista Sr.",       docs: 154, validation: 94.8, hours: 132, lastActivity: "hace 38 min", online: true  },
      { name: "Andrés Bedoya",      email: "a.bedoya@sb.com.co",      role: "Analista Jr.",       docs: 128, validation: 93.2, hours: 118, lastActivity: "hace 52 min", online: true  },
      { name: "Camila Ríos",        email: "c.rios@sb.com.co",        role: "Revisora",            docs: 112, validation: 99.4, hours: 98,  lastActivity: "hace 1 h",    online: false },
      { name: "Jorge Mendoza",      email: "j.mendoza@sb.com.co",     role: "Actuario",            docs: 88,  validation: 97.8, hours: 86,  lastActivity: "ayer",        online: false },
    ],
    feed: [
      { user: "Laura G.",    type: "edit",     action: "editó",                 target: "poliza_2026_0412",           time: "hace 11 min", pages: 14 },
      { user: "Felipe T.",   type: "validate", action: "validó con IA",         target: "siniestro_auto_332",         time: "hace 27 min", pages: 22 },
      { user: "Valentina C.", type: "warn",    action: "señaló discrepancia en", target: "poliza_salud_17",            time: "hace 38 min", detail: "diagnóstico no coincide con CIE-10" },
      { user: "Andrés B.",   type: "nexify",   action: "nexificó",              target: "renovaciones_abril_lote_2",  time: "hace 52 min", pages: 184, duration: "54s" },
      { user: "Camila R.",   type: "validate", action: "validó con IA",         target: "poliza_vida_colectivo_881",   time: "hace 1 h",    pages: 42 },
      { user: "Jorge M.",    type: "edit",     action: "firmó digitalmente",    target: "dictamen_actuarial_Q1",      time: "hace 2 h",    pages: 8 },
      { user: "Laura G.",    type: "split",    action: "dividió",               target: "anexos_poliza_salud.pdf",    time: "hace 2 h",    pages: 26 },
      { user: "Felipe T.",   type: "error",    action: "falló OCR en",          target: "siniestro_122_manuscrito",   time: "hace 3 h",    detail: "páginas 8-11 ilegibles" },
    ],
  },
};

window.NEXA_ORGS = NEXA_ORGS;
